POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Raluca",
  "lastName": "Stefania",
  "email": "raluca@stefania.com",
  "password": "Lov3wins291!",
  "trips": [{
      "title": "MySecondTRip",
      "cities": ["Heidelberg", "Hamburg", "München", "Köln"],
      "middlePoint": "Regensburg"
      }]
}

###

DELETE http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjBjYzgxZWM2Yzk4OTY1ODRlOWJiMWZmIiwiaWF0IjoxNjI0MDE2NDMxfQ.bSxe7Sn2BFEVRtEdRqRCE-2OPcMw6lXi-gpruCw3zyw

###

PUT http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjBmZTk0NjA0OGI1YWUxZGNmYzcwNjcyIiwiaWF0IjoxNjI3Mjk4OTU3fQ.W6ru4FtlfRU-PNh4oNTtJSPtziRwmCm7xAk-BNaDfoQ

{
  "trips": [{
      "title": "My First Trip",
      "cities": ["Heidelberg", "Hamburg", "Muenchen", "Koeln"]
      },
      {
      "title": "My Second Trip",
      "cities": ["Berlin", "Barcelona", "Paris"]
      },
      {
      "title": "Unforgettable Trip",
      "cities": ["Regensburg", "Berlin", "Passau", "Ulm"]
      },
      {
      "title": "BIG Trip",
      "cities": ["New York", "Dubai", "Tokyo", "Berlin"]
      },
      {
      "title": "RO Trip",
      "cities": ["Aglasterhausen", "Oradea", "Philadelphia", "Borozel"]
      }]
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "raluca@bochis.com",
  "password": "Lov3wins291!"
}

###

GET  http://localhost:8080/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjBmZTk0NjA0OGI1YWUxZGNmYzcwNjcyIiwiaWF0IjoxNjI3Mjk4OTU3fQ.W6ru4FtlfRU-PNh4oNTtJSPtziRwmCm7xAk-BNaDfoQ