POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Raluca",
  "lastName": "Stefania",
  "email": "raluca@stefania.com",
  "password": "parola",
  "trips": [{
      "title": "MySecondTRip",
      "cities": ["Heidelberg", "Hamburg", "München", "Köln"],
      "middlePoint": "Regensburg"
      }]
}

###

DELETE http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjBjYzgxZWM2Yzk4OTY1ODRlOWJiMWZmIiwiaWF0IjoxNjI0MDE2NDMxfQ.bSxe7Sn2BFEVRtEdRqRCE-2OPcMw6lXi-gpruCw3zyw

###

PUT http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjBlMzAzNDU1MmE4ODA5Yzk2MjcwMjI1IiwiaWF0IjoxNjI1NDkwMjk1fQ.YfpTDhBHrC9pcXzE3BURrnyNtyIv3Y9aENhJtmdshEM

{
  "trips": [{
      "title": "MySecondTRip",
      "cities": ["Heidelberg", "Hamburg", "München", "Köln"],
      "middlePoint": "Regensburg"
      }]
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "raluca@stefania.com",
  "password": "parola"
}

###

GET  http://localhost:8080/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjBlMzAzNDU1MmE4ODA5Yzk2MjcwMjI1IiwiaWF0IjoxNjI1NDkwMjk1fQ.YfpTDhBHrC9pcXzE3BURrnyNtyIv3Y9aENhJtmdshEM